project/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  root 'posts#index'
  get 'about' => 'pages#about'
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/author.rb
class Author < ApplicationRecord
 #22.12.2020 додав 3-7 строку
 has_many :posts
 has_many :comments
  def full_name
    "#{self.first_name} #{self.last_name} "
  end
end

project/app/models/authortest.rb
class Authortest < ApplicationRecord
end

project/app/models/comment.rb
class Comment < ApplicationRecord
  #belongs_to :post, required: true
  #belongs_to :author, required: true
  enum status: [ :unpublished, :published ]
 # validates :body, presence: true, length: { minimum: 5 }
  #22.12.2020 додав 2-5 строку
end

project/app/models/post.rb
class Post < ApplicationRecord
 belongs_to :author,:optional => true

  has_many :comments, dependent: :destroy
# Додано 2 і 3 строку
  validates :title, presence: true
  validates :content, presence: true
  validates :title, length: { maximum: 20 }
  validates :content, length: { maximum: 300 }
end

project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :status, :user_id, :post_id)
    end
end

project/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@heading = 'about'
		@text = 'text'
	end
end

project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  # --->Додав  код в def show
  @comment_status = params[:comments_status].to_s.downcase
  @comments = if @comment_status == 'unpublished'
  @post.comments.unpublished
    else
     @post.comments.published
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :image)
    end
end

project/app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

project/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Status</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.status %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

project/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

project/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Status:</strong>
  <%= @comment.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project7</title>

   <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 	<header>
<nav class="navbar navbar-expand-lg navbardark fixed-top scrolling-navbar">
	<div class="container">
		<a href="https://docs.google.com/forms/d/e/1FAIpQLSfc8Ecox_tOKLJneaHfDptW-j4Sgi-CM0MieQbwgd_38GS8Ng/viewform" class="navbar-brand">HW7</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNaw" aria-controls="basicExampleNaw" aria-expanded="false" aria-label="Toggle Navigation">
			<span class="navbar-toggler-icon"></span>
			
		</button>
<div class="collapse navbar-collapse" id=basicExampleNaw>
	<ul class="navbar-nav mr-auto smooth-scroll">
		<li class="nav-item">
			<a href="http://localhost:3000/" class="nav-link waves-effect waves-light">Home</a>	
		</li>
				<li class="nav-item">
			<a href="http://localhost:3000/posts" class="nav-link waves-effect waves-light">posts</a>	
		</li>
				<li class="nav-item">
			<a href="http://localhost:3000/about" class="nav-link waves-effect waves-light">about</a>	
		</li>
        </li>
        <li class="nav-item">
      <a href="http://localhost:3000/comments" class="nav-link waves-effect waves-light">comments</a> 
    </li>
	</ul>
</div>

	</div>
</nav>

</header>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  <body>
    <%= yield %>
  </body>
</html>

project/app/views/pages/about.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>about</title>
  </head>
  <body>

<div class="wrapper">

  <div class="content"></div>

  <div class="footer"></div>

</div>

  	<header>
<nav class="navbar navbar-expand-lg navbardark fixed-top scrolling-navbar">
	<div class="container">
		<a href="https://docs.google.com/forms/d/e/1FAIpQLSfc8Ecox_tOKLJneaHfDptW-j4Sgi-CM0MieQbwgd_38GS8Ng/viewform" class="navbar-brand">HW7</a>
			
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNaw" aria-controls="basicExampleNaw" aria-expanded="false" aria-label="Toggle Navigation">
			<span class="navbar-toggler-icon"></span>
			
			</button>
<div class="collapse navbar-collapse" id=basicExampleNaw>
	<ul class="navbar-nav mr-auto smooth-scroll">
		<li class="nav-item">
			<a href="http://localhost:3000/" class="nav-link waves-effect waves-light">Home</a>	
		</li>
				<li class="nav-item">
			<a href="http://localhost:3000/posts" class="nav-link waves-effect waves-light">posts</a>	
		</li>
				<li class="nav-item">
			<a href="http://localhost:3000/about" class="nav-link waves-effect waves-light">about</a>	</li>
              <li class="nav-item">
      <a href="http://localhost:3000/comments" class="nav-link waves-effect waves-light">comments</a> 
    </li>
	</ul>
</div>

	</div>
</nav>
</header>


<main>

<div id="intro" class="view">
   <div class="mask rgba-black-strong">
	<div class="container-fluid d-flex aling-items-center justify-content-center h-100">
     <div class="row d-flex justify-content-center text-center">
	  <div class="col-md-10">

			<hr class="hr-light">
			<h4 class="white-text my-4"> </h4>			
	  </div>
	 </div>
	</div>	
   </div>
  </div>

<div>
	<p><h1 class="text-center">RoR GH 20/21 Homework 7</h1></p>
	<p><h4>Нужно сгенерировать рельсовый проект и сгенерировать сущность Posts используя скафолд. Установить бутстрап гем, использовать его для вьюх (добавить вёрстку во вьюхах).</h4></p>
	<p class="text-center"><h4>Шаги:</h4></p>
<ol>
   <li>Настроить RubyMine (или удобный для вас редактор)</li>
   <li>Установить RoR 6.1 (gem install rails)</li>
   <li>Убедиться что установлена нужная версия рельс (rails -v)</li>
   <li>Сгенерировать рельсовый проект (rails new project_name)</li>
   <li>Сгенерировать сущности Post используя скафолд и затем прогнать миграцию</li>
   <ul>
     <li>rails generate scaffold Post name:string title:string content:text image:string</li>
     <li>rake db:migrate</li>
 </ul>
   <li>Запустить проект (убедиться что всё работает)</li>
   <li>Установить бутстрап</li>
   <li>Применить вёрстку используя бутстрап</li>
   <li>Использовать обязательно RVM или rbenv</li>
   <li> Настроить свою IDE или Text Editor согласно Ruby style code (два пробела, а не таб и т.д.)</li>
   <li>сделать страницу постов (index) корневой страницей проекта</li>
   <li>добавить валидацию (проверку наличия данных, максимального размера для title) полей поста (title, content)</li>
   <li>создать модель Author (только модель (rails g model), таблица будет заполняться с помощью seed, создать 5 авторов)</li>
   <li>Поля автора: first_name, last_name, gender, birthday (сгенерировать данные с помощью гема faker, тип полей в соответсвии с назначением (string, datetime))</li>
   <li> при создании или редактировании поста - автора мы должны выбирать с помощью выпадающего списка.</li>
   <li>Поле image – url. Выводить на странице поста между title и description через хелпер/метод image_tag.</li>
   <li>Залить на Хероку.</li>
</ol>
</div>








    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  
</main>
 <!-- <footer>
  	<div class="text-center">Copyright 2020</div>
  </footer>-->
  </body>
</html>

project/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

project/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.image %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

project/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %> 
<%= link_to 'Back', posts_path, class: 'btn btn-outline-dark' %>

project/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>