hwblog/config/routes.rb
Rails.application.routes.draw do
  resources :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'posts#index', as: 'home'
get 'about' => 'pages#about', as:'about'
get 'cv' => 'pages#cv', as:'cv'
get 'users' => 'pages#users', as:'users'
get 'sitemap' => 'pages#sitemap', as:'sitemap'
resources :posts do
resources :comments
end
end

hwblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hwblog/app/models/author.rb
class Author < ApplicationRecord
#validates :title, presence: true
#validates :title, length: { maximum: 20 }
#validates :title, presence: true
#validates :title, length: { minimum: 5 }
end

hwblog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

hwblog/app/models/post.rb
class Post < ApplicationRecord
has_many :comments
validates :title, presence: true
validates :title, length: { maximum: 20 }
validates :title, presence: true
validates :title, length: { minimum: 5 }
end

hwblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hwblog/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :gender, :birthday, :short_information)
    end
end

hwblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
#http_basic_authenticate_with name: "admin", password: "1111"
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end
  private def comment_params
  	params.require(:comment).permit(:username, :body)
  end
end

hwblog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@heading = 'Pages about us'
	end

	def cv
		
	end
end

hwblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
 http_basic_authenticate_with name: "admin", password: "1111",
 	exept: [:index, :show]


	def index
	  @post = Post.all
	end
#----------------
	def new
  @post =Post.new
	end
#----------------
	def show
	  @post = Post.find(params[:id])
	end
#----------------
	def edit
	  @post = Post.find(params[:id])
	end
#----------------
	def update
	  @post = Post.find(params[:id])

	  if(@post.update(post_params))
	  redirect_to @post
	 else
	 	render 'edit'
	 end
	end
#----------------
	def destroy
	  @post = Post.find(params[:id])

	  @post.destroy
	  redirect_to posts_path	
	end
#----------------
	def create
	# render plain: params[:post].inspect	
	@post = Post.new(post_params)

	if(@post.save)
	  redirect_to @post
	 else
	 	render 'new'
	 end
	end
#----------------
  private def post_params
  	params.require(:post).permit(:title, :body)
  	
  end
end

hwblog/app/helpers/application_helper.rb
module ApplicationHelper
end

hwblog/app/helpers/authors_helper.rb
module AuthorsHelper
end

hwblog/app/helpers/comments_helper.rb
module CommentsHelper
end

hwblog/app/helpers/pages_helper.rb
module PagesHelper
end

hwblog/app/helpers/posts_helper.rb
module PostsHelper
end

hwblog/app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :short_information %>
    <%= form.text_area :short_information %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hwblog/app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

hwblog/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Birthday</th>
      <th>Short information</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= author.gender %></td>
        <td><%= author.birthday %></td>
        <td><%= author.short_information %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

hwblog/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

hwblog/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @author.gender %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @author.birthday %>
</p>

<p>
  <strong>Short information:</strong>
  <%= @author.short_information %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

hwblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hwblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header> 
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="h5 my-0 mr-md-auto font-weight-bold">RoR GH 20/21 Homework</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <span class="p-2 text-dark"><%= link_to "Main page", home_path %></span>
    <span class="p-2 text-dark"><%= link_to "Add articles", new_post_path %></span>
    <span class="p-2 text-dark"><%= link_to "Authors", authors_path %></span>
    <span class="p-2 text-dark"><%= link_to "About us", about_path %></span>
    <span class="p-2 text-dark"><%= link_to "CV", cv_path %></span>
  </nav>  
    
  
  <a class="btn btn-outline-primary" href="#">Sign up</a>
  </div>
</header>
<div class="container">
    <%= yield %>
</div>

<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
       <a> <%= link_to "Sitemap", sitemap_path %> </a>
  </div>
  <!-- Copyright -->
</footer>
  </body>
</html>

hwblog/app/views/pages/about.html.erb
<h2 align="center">Here links to homework</h2>
  <div>
	<p><a href="https://docs.google.com/forms/d/e/1FAIpQLSfAY3RRK0iEFPGfGPA6HQVv10J2gXNvw2sCyE6fbOBBePQkig/viewform">RoR GH 20/21 Homework 6</a></p> 	
	<p><a href="https://docs.google.com/forms/d/e/1FAIpQLSfc8Ecox_tOKLJneaHfDptW-j4Sgi-CM0MieQbwgd_38GS8Ng/viewform">RoR GH 20/21 Homework 7</a></p>
	<p><a href="https://docs.google.com/forms/d/e/1FAIpQLScfM-xc6adrEKdE9oerKrTGG6W1ZDr-ZUct6OIIo1ZBzzsWEg/viewform">RoR GH 20/21 Homework 8</a></p>
	<p><a href="https://docs.google.com/forms/d/e/1FAIpQLSfLfSGmYsCWnlVMqbfz21z-OGnxWkKVMVtX1jcngxufOgJsYg/viewform">RoR GH 20/21 Homework 9</a></p>
  </div>

hwblog/app/views/pages/cv.html.erb
<h2 align="center">Example cv</h2>
<div class="cv-wrapper">
  <div class="cv">
    <div class="header">
      <div class="info">
        <div class="main">
          <h1 class="name">Enter your: Name, Surname</h1>
          <h2 class="position">Please enter your: Position</h2>
        </div>
           <div class="contacts">
            <p class="contacts-item"><i class="far fa-envelope"></i> Enter your: Mail</p>
            <p class="contacts-item"><i class="fas fa-phone"></i> Enter your: Phone</p>
            <p class="contacts-item"><i class="fas fa-map-marker-alt"></i> Enter your: Location</p>
           </div>
            </div>
             <div class="photo-wrapper">
              <img src="https://st.depositphotos.com/1779253/5140/v/600/depositphotos_51405259-stock-illustration-male-avatar-profile-picture-use.jpg" alt="Photo" class="photo">
             </div>
</div>

  
<div class="footer">

  <div class="section">
    <h3>Section of your Education</h3>
    <ul class="section-list">
    <li>Enter your: Education Period from ____ to ____</li>
    <li>Enter your: Education Period from ____ to ____</li>
    <li>Enter your: Education Period from ____ to ____</li>
    </ul>
  </div>

  <div class="section">
    <h3>Section of your skills</h3>
    <ul class="section-list">
    <li>Enter your: Skills</li>
    <li>Enter your: Skills</li>
    <li>Enter your: Skills</li>
    </ul>
  </div>

  <div class="section">
    <h3>Section of your experience</h3>
    <ul class="section-list">
    <li>Enter your: Experience Period from ____ to ____</li>
    <li>Enter your: Experience Period from ____ to ____</li>
    <li>Enter your: Experience Period from ____ to ____</li>
    </ul>
  </div>

  <div class="section">
    <h3>Section Favorite free time activity</h3>
    <ul class="section-list">
    <li>Enter your: Favorite free time activity</li>
    </ul>
  </div>

    </div>
  </div>
</div>

hwblog/app/views/pages/sitemap.html.erb
<div>
	<p><h2 align="center">Instead of all the usual sitemap, information about the pages that we have will be temporarily displayed here until I do everything in its normal form.</h2></p>
</div>

<div>
	<p><%= link_to "Main page", home_path %></p> 	
	<p><%= link_to "Add articles", new_post_path %></p>
	<p><%= link_to "About us", about_path %></p>
	<p><%= link_to "CV", cv_path %></p>
	<p><%= link_to "sitemap", sitemap_path %></p>
	<p><%= link_to "authors", authors_path %></p>
	<p><%= link_to "users", users_path %></p>
	<p><%= link_to "posts", posts_path %></p>
</div>

hwblog/app/views/pages/users.html.erb
<h2 align="center">Users page</h2>

hwblog/app/views/posts/edit.html.erb
<h2>Editing post</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'> <%= msg %> </div>
      <% end %>
    <% end %>
<p>
	Name<br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
	Text article<br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-success'}) %>
</p>
<% end %>

hwblog/app/views/posts/index.html.erb
<h1>All posts</h1>
<% @post.each do |post| %>
<div class="well">
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
  <%= link_to "Read more", post_path(post), :class => 'btn btn-link' %>
</div>
<% end %>

hwblog/app/views/posts/new.html.erb
<h2>Add new post</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'> <%= msg %> </div>
      <% end %>
    <% end %>
<p>
	Name<br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
	Text article<br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-success'}) %>
</p>
<% end %>

hwblog/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Do you want delete this article?"}, :class => 'btn btn-danger' %>

<hr>
<h1>All comments</h1>
<% @post.comments.each do |comment| %>
<div class="alert alert-light">
  <p><strong><%= comment.username %></strong> <%= comment.body%></p>
</div>
<% end %>

<hr>
<h2>Add comments</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
	User<br>
	<%= f.text_field(:username, {:class => 'form-control'}) %>
</p>

<p>
	Text commentaries<br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.submit("Add comment", {:class => 'btn btn-warning'}) %>
</p>
<% end %>